//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCodeGenerator.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDarkTheme
        {
            get
            {
                return ((bool)(this["UseDarkTheme"]));
            }
            set
            {
                this["UseDarkTheme"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLineNumbers
        {
            get
            {
                return ((bool)(this["UseLineNumbers"]));
            }
            set
            {
                this["UseLineNumbers"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LineNumberStart
        {
            get
            {
                return ((int)(this["LineNumberStart"]));
            }
            set
            {
                this["LineNumberStart"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LineNumberStep
        {
            get
            {
                return ((int)(this["LineNumberStep"]));
            }
            set
            {
                this["LineNumberStep"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseComments
        {
            get
            {
                return ((bool)(this["UseComments"]));
            }
            set
            {
                this["UseComments"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowArcs
        {
            get
            {
                return ((bool)(this["AllowArcs"]));
            }
            set
            {
                this["AllowArcs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsePaddedGCodes
        {
            get
            {
                return ((bool)(this["UsePaddedGCodes"]));
            }
            set
            {
                this["UsePaddedGCodes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpindleControlEnabled
        {
            get
            {
                return ((bool)(this["SpindleControlEnabled"]));
            }
            set
            {
                this["SpindleControlEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpindleSpeedEnabled
        {
            get
            {
                return ((bool)(this["SpindleSpeedEnabled"]));
            }
            set
            {
                this["SpindleSpeedEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12000")]
        public int SpindleSpeedRpm
        {
            get
            {
                return ((int)(this["SpindleSpeedRpm"]));
            }
            set
            {
                this["SpindleSpeedRpm"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpindleStartEnabled
        {
            get
            {
                return ((bool)(this["SpindleStartEnabled"]));
            }
            set
            {
                this["SpindleStartEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M3")]
        public string SpindleStartCommand
        {
            get
            {
                return ((string)(this["SpindleStartCommand"]));
            }
            set
            {
                this["SpindleStartCommand"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpindleStopEnabled
        {
            get
            {
                return ((bool)(this["SpindleStopEnabled"]));
            }
            set
            {
                this["SpindleStopEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpindleDelayEnabled
        {
            get
            {
                return ((bool)(this["SpindleDelayEnabled"]));
            }
            set
            {
                this["SpindleDelayEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double SpindleDelaySeconds
        {
            get
            {
                return ((double)(this["SpindleDelaySeconds"]));
            }
            set
            {
                this["SpindleDelaySeconds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CoolantControlEnabled
        {
            get
            {
                return ((bool)(this["CoolantControlEnabled"]));
            }
            set
            {
                this["CoolantControlEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CoolantStartEnabled
        {
            get
            {
                return ((bool)(this["CoolantStartEnabled"]));
            }
            set
            {
                this["CoolantStartEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CoolantStopEnabled
        {
            get
            {
                return ((bool)(this["CoolantStopEnabled"]));
            }
            set
            {
                this["CoolantStopEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddStartPosition
        {
            get
            {
                return ((bool)(this["AddStartPosition"]));
            }
            set
            {
                this["AddStartPosition"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StartX
        {
            get
            {
                return ((double)(this["StartX"]));
            }
            set
            {
                this["StartX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StartY
        {
            get
            {
                return ((double)(this["StartY"]));
            }
            set
            {
                this["StartY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StartZ
        {
            get
            {
                return ((double)(this["StartZ"]));
            }
            set
            {
                this["StartZ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddEndPosition
        {
            get
            {
                return ((bool)(this["AddEndPosition"]));
            }
            set
            {
                this["AddEndPosition"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EndX
        {
            get
            {
                return ((double)(this["EndX"]));
            }
            set
            {
                this["EndX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EndY
        {
            get
            {
                return ((double)(this["EndY"]));
            }
            set
            {
                this["EndY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EndZ
        {
            get
            {
                return ((double)(this["EndZ"]));
            }
            set
            {
                this["EndZ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetWorkCoordinateSystem
        {
            get
            {
                return ((bool)(this["SetWorkCoordinateSystem"]));
            }
            set
            {
                this["SetWorkCoordinateSystem"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G54")]
        public string WorkCoordinateSystem
        {
            get
            {
                return ((string)(this["WorkCoordinateSystem"]));
            }
            set
            {
                this["WorkCoordinateSystem"] = value;
            }
        }
    }
}
