using System;
using System.Globalization;
using System.Linq;
using GCodeGenerator.GCodeGenerators;
using GCodeGenerator.Models;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace GCodeGenerator.Tests
{
    /// <summary>
    /// Юнит-тесты ProgramBuilder (пункт 4.1 плана): структурированное
    /// построение программы — слова, порядок, типы.
    /// </summary>
    [TestClass]
    public class ProgramBuilderTests
    {
        private static GCodeProgram _program;
        private static ProgramBuilder _builder;

        [TestInitialize]
        public void Setup()
        {
            _program = new GCodeProgram();
            _builder = new ProgramBuilder(_program);
        }

        /// <summary>Описывает блок в виде "G:0 X:10(3) ..." для сравнения.</summary>
        private static string Describe(GCodeBlock block)
        {
            if (block.Words.Count == 0)
                return $"({block.Comment})";
            return string.Join(" ", block.Words.Select(w =>
                w.Text != null ? $"RAW[{w.Text}]" : $"{w.Letter}:{w.Number.ToString(CultureInfo.InvariantCulture)}({w.Decimals})"));
        }

        private static void AssertBlock(int index, string expected)
        {
            Assert.IsTrue(index < _program.Blocks.Count, $"Нет блока {index}");
            Assert.AreEqual(expected, Describe(_program.Blocks[index]));
        }

        [TestMethod]
        public void RapidTo_XyFeed()
        {
            _builder.RapidTo(x: 10.0, y: 20.0, feed: 1000.0, decimals: 3);
            AssertBlock(0, "G:0(-1) X:10(3) Y:20(3) F:1000(3)");
        }

        [TestMethod]
        public void RapidTo_ZFeed()
        {
            _builder.RapidTo(z: 1.0, feed: 500.0, decimals: 3);
            AssertBlock(0, "G:0(-1) Z:1(3) F:500(3)");
        }

        [TestMethod]
        public void LinearTo_ZFeed()
        {
            _builder.LinearTo(z: -1.0, feed: 200.0, decimals: 3);
            AssertBlock(0, "G:1(-1) Z:-1(3) F:200(3)");
        }

        [TestMethod]
        public void LinearTo_XyzFeed()
        {
            _builder.LinearTo(x: 5.0, y: 6.0, z: -2.0, feed: 300.0, decimals: 3);
            AssertBlock(0, "G:1(-1) X:5(3) Y:6(3) Z:-2(3) F:300(3)");
        }

        [TestMethod]
        public void ArcCW_Words()
        {
            _builder.ArcCW(10.0, 0.0, 5.0, 0.0, 300.0, 3);
            AssertBlock(0, "G:2(-1) X:10(3) Y:0(3) I:5(3) J:0(3) F:300(3)");
        }

        [TestMethod]
        public void ArcCCW_Words()
        {
            _builder.ArcCCW(10.0, 0.0, 5.0, 0.0, 300.0, 3);
            AssertBlock(0, "G:3(-1) X:10(3) Y:0(3) I:5(3) J:0(3) F:300(3)");
        }

        [TestMethod]
        public void HelicalArc_Words()
        {
            _builder.ArcCW(10.0, 0.0, 5.0, 0.0, 300.0, 3, z: -1.0);
            AssertBlock(0, "G:2(-1) X:10(3) Y:0(3) Z:-1(3) I:5(3) J:0(3) F:300(3)");
        }

        [TestMethod]
        public void Dwell_Words()
        {
            _builder.Dwell(2000.0);
            AssertBlock(0, "G:4(-1) P:2000(-1)");
        }

        [TestMethod]
        public void SpindleOn_WithSpeed()
        {
            _builder.SpindleOn("M3", 12000);
            AssertBlock(0, "M:3(-1) S:12000(-1)");
        }

        [TestMethod]
        public void SpindleOn_CounterClockwise_NoSpeed()
        {
            _builder.SpindleOn("M4");
            AssertBlock(0, "M:4(-1)");
        }

        [TestMethod]
        public void SpindleOff_CoolantOn_CoolantOff()
        {
            _builder.SpindleOff();
            _builder.CoolantOn();
            _builder.CoolantOff();
            AssertBlock(0, "M:5(-1)");
            AssertBlock(1, "M:8(-1)");
            AssertBlock(2, "M:9(-1)");
        }

        [TestMethod]
        public void Comment_Block()
        {
            _builder.Comment("Pass 1, depth -1.000");
            AssertBlock(0, "(Pass 1, depth -1.000)");
        }

        [TestMethod]
        public void Header_Block()
        {
            // Legacy behavior: header is a raw marker line (emitted even with
            // comments disabled).
            _builder.Header();
            AssertBlock(0, "RAW[(Generated by GCodeGenerator)]");
        }

        [TestMethod]
        public void SetWcs_Block()
        {
            _builder.SetWcs("G55");
            AssertBlock(0, "G:55(-1)");
        }

        [TestMethod]
        public void SetWcs_Invalid_Throws()
        {
            Assert.Throws<ArgumentException>(() => _builder.SetWcs("G0"));
            Assert.Throws<ArgumentException>(() => _builder.SetWcs("G60"));
            Assert.Throws<ArgumentException>(() => _builder.SetWcs(""));
        }

        [TestMethod]
        public void SetStartPosition_RawG92()
        {
            _builder.SetStartPosition(0.0, 0.0, 5.0);
            AssertBlock(0, "RAW[G92] X:0(-1) Y:0(-1) Z:5(-1)");
        }

        [TestMethod]
        public void SetEndPosition_SplitsVerticalAndHorizontalRapids()
        {
            _builder.SetEndPosition(100.0, 0.0, -2.0, 5.0);
            AssertBlock(0, "G:0(-1) Z:5(-1)");
            AssertBlock(1, "G:0(-1) X:100(-1) Y:0(-1)");
            AssertBlock(2, "G:0(-1) Z:-2(-1)");
        }

        [TestMethod]
        public void EndProgram_RawM30()
        {
            _builder.EndProgram();
            AssertBlock(0, "RAW[M30]");
        }

        [TestMethod]
        public void Sequence_BlocksAccumulate()
        {
            _builder.Header();
            _builder.SetWcs("G54");
            _builder.RapidTo(z: 1.0, feed: 500.0, decimals: 3);
            _builder.EndProgram();
            Assert.AreEqual(4, _program.Blocks.Count);
        }
    }
}
