using System;
using GCodeGenerator.Models;
using GCodeGenerator.Trajectory;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace GCodeGenerator.Tests
{
    /// <summary>
    /// Unit tests for <see cref="SceneBuilder"/> (plan item 6.4): segments
    /// from structured GCodeProgram blocks — modal G state, arc planes,
    /// I/J/K and R arcs, M30/M2, G92, arc interpolation, bounds.
    /// </summary>
    [TestClass]
    public class SceneBuilderTests
    {
        private const double Tol = 1e-9;

        private static GCodeBlock Block(params GCodeWord[] words) => new GCodeBlock(words);

        private static GCodeWord W(char letter, double number, int decimals = 3) => new GCodeWord(letter, number, decimals);

        private static Vec3 Pt(double x, double y, double z) => new Vec3(x, y, z);

        private static void AssertPoint(Vec3 actual, double x, double y, double z, string what)
        {
            Assert.IsTrue(Math.Abs(actual.X - x) < Tol && Math.Abs(actual.Y - y) < Tol && Math.Abs(actual.Z - z) < Tol,
                $"{what}: expected ({x}, {y}, {z}), got {actual}");
        }

        // ------------------------------------------------------------------
        // Basics
        // ------------------------------------------------------------------

        [TestMethod]
        public void EmptyProgram_ProducesEmptyScene()
        {
            var scene = SceneBuilder.Build(new GCodeProgram());
            Assert.IsTrue(scene.IsEmpty);
            Assert.IsNull(scene.Bounds);
        }

        [TestMethod]
        public void NullProgram_ProducesEmptyScene()
        {
            var scene = SceneBuilder.Build(null);
            Assert.IsTrue(scene.IsEmpty);
        }

        [TestMethod]
        public void RapidAndLinear_Segments()
        {
            var program = new GCodeProgram();
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 5)));
            program.Blocks.Add(Block(GCodeWord.G(1), W('X', 10), W('Y', 20)));

            var scene = SceneBuilder.Build(program);
            Assert.AreEqual(2, scene.Segments.Count);

            var s0 = scene.Segments[0];
            Assert.AreEqual(MoveType.Rapid, s0.MoveType);
            AssertPoint(s0.Start, 0, 0, 0, "s0.Start");
            AssertPoint(s0.End, 0, 0, 5, "s0.End");

            var s1 = scene.Segments[1];
            Assert.AreEqual(MoveType.Linear, s1.MoveType);
            AssertPoint(s1.Start, 0, 0, 5, "s1.Start");
            AssertPoint(s1.End, 10, 20, 5, "s1.End");
        }

        [TestMethod]
        public void ModalMoveType_PersistsUntilChanged()
        {
            var program = new GCodeProgram();
            program.Blocks.Add(Block(GCodeWord.G(1), W('X', 1)));
            program.Blocks.Add(Block(W('X', 2))); // no G word → stays Linear
            program.Blocks.Add(Block(GCodeWord.G(0), W('X', 3)));

            var scene = SceneBuilder.Build(program);
            Assert.AreEqual(3, scene.Segments.Count);
            Assert.AreEqual(MoveType.Linear, scene.Segments[0].MoveType);
            Assert.AreEqual(MoveType.Linear, scene.Segments[1].MoveType);
            Assert.AreEqual(MoveType.Rapid, scene.Segments[2].MoveType);
        }

        [TestMethod]
        public void LastMotionGInLine_Wins()
        {
            var program = new GCodeProgram();
            program.Blocks.Add(Block(GCodeWord.G(1), GCodeWord.G(0), W('X', 1)));

            var scene = SceneBuilder.Build(program);
            Assert.AreEqual(MoveType.Rapid, scene.Segments[0].MoveType);
        }

        [TestMethod]
        public void SamePosition_NoSegment()
        {
            var program = new GCodeProgram();
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 5)));
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 5))); // no position change

            var scene = SceneBuilder.Build(program);
            Assert.AreEqual(1, scene.Segments.Count);
        }

        [TestMethod]
        public void CommentAndHeaderBlocks_AreSkipped()
        {
            var program = new GCodeProgram();
            program.Blocks.Add(new GCodeBlock(null, "Profile: test"));
            program.Blocks.Add(Block(GCodeWord.Raw("(Generated by GCodeGenerator)")));
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 5)));

            var scene = SceneBuilder.Build(program);
            Assert.AreEqual(1, scene.Segments.Count);
        }

        [TestMethod]
        public void M30_Line_IsSkipped()
        {
            // Как и в старом текстовом парсере, SceneBuilder пропускает только
            // саму строку M30 (в генерируемых программах M30 всегда последняя);
            // блоки после неё обрабатываются.
            var program = new GCodeProgram();
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 5)));
            program.Blocks.Add(Block(GCodeWord.Raw("M30")));
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 10)));

            var scene = SceneBuilder.Build(program);
            Assert.AreEqual(2, scene.Segments.Count);
            AssertPoint(scene.Segments[1].End, 0, 0, 10, "move after M30 line");
        }

        [TestMethod]
        public void M2_Line_IsSkipped()
        {
            var program = new GCodeProgram();
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 5)));
            program.Blocks.Add(Block(GCodeWord.M(2)));
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 10)));

            var scene = SceneBuilder.Build(program);
            Assert.AreEqual(2, scene.Segments.Count);
            AssertPoint(scene.Segments[1].End, 0, 0, 10, "move after M2 line");
        }

        [TestMethod]
        public void G92_UpdatesPositionWithoutSegment()
        {
            var program = new GCodeProgram();
            program.Blocks.Add(Block(GCodeWord.Raw("G92"), W('X', 10, -1), W('Z', 5, -1)));
            program.Blocks.Add(Block(GCodeWord.G(0), W('Z', 10)));

            var scene = SceneBuilder.Build(program);
            Assert.AreEqual(1, scene.Segments.Count);
            // G92 updated the tracked position: the move starts from (10, 0, 5)
            AssertPoint(scene.Segments[0].Start, 10, 0, 5, "start after G92");
            AssertPoint(scene.Segments[0].End, 10, 0, 10, "end");
        }

        // ------------------------------------------------------------------
        // Arcs
        // ------------------------------------------------------------------

        [TestMethod]
        public void Arc_IJK_XYPlane_QuarterArc()
        {
            var program = new GCodeProgram();
            // (10,0) → (0,10) around center (0,0), CCW: I = -10, J = 0
            program.Blocks.Add(Block(GCodeWord.G(0), W('X', 10), W('Y', 0)));
            program.Blocks.Add(Block(GCodeWord.G(3), W('X', 0), W('Y', 10), W('I', -10), W('J', 0), W('F', 100)));

            var scene = SceneBuilder.Build(program);
            var seg = scene.Segments[1];
            Assert.AreEqual(MoveType.ArcCCW, seg.MoveType);
            AssertPoint(seg.ArcCenter.Value, 0, 0, 0, "center");
            Assert.IsTrue(Math.Abs(seg.ArcRadius - 10) < Tol, $"radius: {seg.ArcRadius}");
            Assert.IsNotNull(seg.InterpolatedPoints);

            // quarter circle → totalAngle = π/2 → segments = max((int)(8), 4) = 8 → 9 points
            Assert.AreEqual(9, seg.InterpolatedPoints.Count);
            AssertPoint(seg.InterpolatedPoints[0], 10, 0, 0, "arc start");
            AssertPoint(seg.InterpolatedPoints[seg.InterpolatedPoints.Count - 1], 0, 10, 0, "arc end");
            // midpoint at 45°: (10·cos45, 10·sin45)
            AssertPoint(seg.InterpolatedPoints[4], 10 * Math.Sqrt(2) / 2, 10 * Math.Sqrt(2) / 2, 0, "arc midpoint");
        }

        [TestMethod]
        public void Arc_R_Positive_Clockwise()
        {
            var program = new GCodeProgram();
            // (0,0) → (10,0), R=10, G2: center (5, -√75)
            program.Blocks.Add(Block(GCodeWord.G(2), W('X', 10), W('Y', 0), W('R', 10), W('F', 100)));

            var scene = SceneBuilder.Build(program);
            var seg = scene.Segments[0];
            Assert.AreEqual(MoveType.ArcCW, seg.MoveType);
            Assert.IsTrue(Math.Abs(seg.ArcRadius - 10) < Tol, $"radius: {seg.ArcRadius}");
            Assert.IsNotNull(seg.InterpolatedPoints);

            // 60° arc → segments = max((int)(1.0472/0.19635), 4) = 5 → 6 points
            Assert.AreEqual(6, seg.InterpolatedPoints.Count);
            AssertPoint(seg.InterpolatedPoints[0], 0, 0, 0, "arc start");
            AssertPoint(seg.InterpolatedPoints[5], 10, 0, 0, "arc end");
            // point 3 of 6 (t = 0.6): angle = 120° − 0.6·60° = 84° = 7π/15
            // from center (5, −√75): (5 + 10·cos84°, −√75 + 10·sin84°)
            var angle = 7.0 * Math.PI / 15.0;
            AssertPoint(seg.InterpolatedPoints[3],
                5 + 10 * Math.Cos(angle), -Math.Sqrt(75) + 10 * Math.Sin(angle), 0, "arc point 3");
        }

        [TestMethod]
        public void Arc_R_Negative_TakesTheLongWay()
        {
            var program = new GCodeProgram();
            // (0,0) → (10,0), R=-10, G2: center (5, +√75), 300° arc
            program.Blocks.Add(Block(GCodeWord.G(2), W('X', 10), W('Y', 0), W('R', -10), W('F', 100)));

            var scene = SceneBuilder.Build(program);
            var seg = scene.Segments[0];
            Assert.AreEqual(MoveType.ArcCW, seg.MoveType);
            Assert.IsNotNull(seg.InterpolatedPoints);

            // 300° arc → segments = max((int)(26.67), 4) = 26 → 27 points
            Assert.AreEqual(27, seg.InterpolatedPoints.Count);
            // midpoint of the 300° sweep: angle -270° ≡ 90° from center (5, +8.6603)
            var mid = seg.InterpolatedPoints[13];
            AssertPoint(mid, 5, Math.Sqrt(75) + 10, 0, "arc midpoint");
        }

        [TestMethod]
        public void Arc_R_TooSmall_FallsBackToLinearPoints()
        {
            var program = new GCodeProgram();
            // chord = 10, |R| = 4 < 5 → linear fallback [start, end]
            program.Blocks.Add(Block(GCodeWord.G(2), W('X', 10), W('Y', 0), W('R', 4), W('F', 100)));

            var scene = SceneBuilder.Build(program);
            var seg = scene.Segments[0];
            Assert.AreEqual(2, seg.InterpolatedPoints.Count);
            AssertPoint(seg.InterpolatedPoints[0], 0, 0, 0, "start");
            AssertPoint(seg.InterpolatedPoints[1], 10, 0, 0, "end");
        }

        [TestMethod]
        public void Arc_SmallAngle_MinimumFourSegments()
        {
            var program = new GCodeProgram();
            // 30° arc around (0,0): (10,0) → (10·cos30, 10·sin30)
            program.Blocks.Add(Block(GCodeWord.G(0), W('X', 10), W('Y', 0)));
            program.Blocks.Add(Block(GCodeWord.G(3), W('X', 10 * Math.Cos(Math.PI / 6)), W('Y', 10 * Math.Sin(Math.PI / 6)), W('I', -10), W('J', 0)));

            var scene = SceneBuilder.Build(program);
            var seg = scene.Segments[1];
            // 30° → (int)(16/6) = 2 → max(2, 4) = 4 → 5 points
            Assert.AreEqual(5, seg.InterpolatedPoints.Count);
        }

        [TestMethod]
        public void Arc_XZPlane_FullCircle_32Segments()
        {
            var program = new GCodeProgram();
            // G18 (XZ): (X=10, Z=0) → (X=10, Z=0) with Y 0→5: full circle in XZ,
            // Y interpolated linearly. Center (0, 0, 0): I = -10, K = 0.
            program.Blocks.Add(Block(GCodeWord.G(18)));
            program.Blocks.Add(Block(GCodeWord.G(0), W('X', 10), W('Z', 0)));
            program.Blocks.Add(Block(GCodeWord.G(2), W('X', 10), W('Z', 0), W('Y', 5), W('I', -10), W('K', 0)));

            var scene = SceneBuilder.Build(program);
            var seg = scene.Segments[1]; // [0] — rapid, G18-блок сегмента не создаёт
            Assert.AreEqual(MoveType.ArcCW, seg.MoveType);
            AssertPoint(seg.ArcCenter.Value, 0, 0, 0, "center");

            // full circle → 32 segments → 33 points
            Assert.AreEqual(33, seg.InterpolatedPoints.Count);
            AssertPoint(seg.InterpolatedPoints[0], 10, 0, 0, "arc start");
            AssertPoint(seg.InterpolatedPoints[32], 10, 5, 0, "arc end (Y moved)");
            // point at a quarter of the CW sweep: angle -90° → (X=0, Z=-10), Y = 1.25
            AssertPoint(seg.InterpolatedPoints[8], 0, 1.25, -10, "arc quarter point");
        }

        [TestMethod]
        public void Arc_YZPlane_QuarterArc()
        {
            var program = new GCodeProgram();
            // G19 (YZ): (Y=10, Z=0) → (Y=0, Z=10) around center (0,0,0): J = -10, K = 0
            program.Blocks.Add(Block(GCodeWord.G(19)));
            program.Blocks.Add(Block(GCodeWord.G(0), W('Y', 10)));
            program.Blocks.Add(Block(GCodeWord.G(3), W('Y', 0), W('Z', 10), W('J', -10), W('K', 0)));

            var scene = SceneBuilder.Build(program);
            var seg = scene.Segments[1]; // [0] — rapid, G19-блок сегмента не создаёт
            Assert.AreEqual(MoveType.ArcCCW, seg.MoveType);
            AssertPoint(seg.ArcCenter.Value, 0, 0, 0, "center");
            Assert.AreEqual(9, seg.InterpolatedPoints.Count);
            // midpoint at 45° from center: (Y = 10·cos45, Z = 10·sin45)
            AssertPoint(seg.InterpolatedPoints[4], 0, 10 * Math.Sqrt(2) / 2, 10 * Math.Sqrt(2) / 2, "arc midpoint");
        }

        [TestMethod]
        public void Arc_WithZMove_InterpolatesThirdAxis()
        {
            var program = new GCodeProgram();
            // (10,0,0) → (0,10,5) around (0,0,0), Z 0→5
            program.Blocks.Add(Block(GCodeWord.G(0), W('X', 10), W('Y', 0)));
            program.Blocks.Add(Block(GCodeWord.G(3), W('X', 0), W('Y', 10), W('Z', 5), W('I', -10), W('J', 0)));

            var scene = SceneBuilder.Build(program);
            var seg = scene.Segments[1];
            AssertPoint(seg.InterpolatedPoints[4], 10 * Math.Sqrt(2) / 2, 10 * Math.Sqrt(2) / 2, 2.5, "arc midpoint with Z");
        }

        // ------------------------------------------------------------------
        // Bounds
        // ------------------------------------------------------------------

        [TestMethod]
        public void Bounds_FromSegmentEnds()
        {
            var program = new GCodeProgram();
            program.Blocks.Add(Block(GCodeWord.G(0), W('X', 10), W('Y', 20), W('Z', 30)));

            var scene = SceneBuilder.Build(program);
            var bounds = scene.Bounds;
            Assert.IsNotNull(bounds);
            AssertPoint(bounds.Value.Min, 0, 0, 0, "min");
            AssertPoint(bounds.Value.Max, 10, 20, 30, "max");
        }

        [TestMethod]
        public void Bounds_FromArcInterpolatedPoints()
        {
            var program = new GCodeProgram();
            // quarter arc (10,0) → (0,10) around (0,0): the arc bulges to (7.07, 7.07),
            // which is inside the (0,0)-(10,10) box, but the start point (10,0) is a corner
            program.Blocks.Add(Block(GCodeWord.G(0), W('X', 10), W('Y', 0)));
            program.Blocks.Add(Block(GCodeWord.G(3), W('X', 0), W('Y', 10), W('I', -10), W('J', 0)));

            var scene = SceneBuilder.Build(program);
            var bounds = scene.Bounds;
            Assert.IsNotNull(bounds);
            AssertPoint(bounds.Value.Min, 0, 0, 0, "min");
            AssertPoint(bounds.Value.Max, 10, 10, 0, "max");
        }
    }
}
