N10 (Generated by GCodeGenerator)
N20 G21 G90 G17 G94
N30 G40 G49 G80
N40 M3 S12000
N50 M8
N60 (Tiny contour: DXF pocket contours: 1, depth 4mm)
N70 (Pass 1, depth -1.000)
N80 (Contour too small for tool, stopping)
N90 M9
N100 M5
N110 M30
