N10 (Generated by GCodeGenerator)
N20 G21 G90 G17 G94
N30 G40 G49 G80
N40 M3 S12000
N50 M8
N60 (Circle below cutoff: Pocket circle R1.55mm, depth 2mm)
N70 (Pass 1, depth -1.000)
N80 (Contour too small for tool, stopping)
N90 M5
N100 M9
N110 M30
