using System;
using System.Collections.Generic;
using GCodeGenerator.Models;

namespace GCodeGenerator.GCodeGenerators
{
    /// <summary>
    /// Builds a structured G-code program (plan item 4.1). Generators emit
    /// semantic moves and commands instead of preformatted strings;
    /// presentation (line numbers, G/M padding, comment visibility) is
    /// applied by <see cref="GCodeFormatter"/> at render time.
    ///
    /// <paramref name="decimals"/> on move methods is the number of decimal
    /// places for the coordinates of that move (the operation's Decimals);
    /// -1 renders plain InvariantCulture values (program preamble).
    /// </summary>
    public class ProgramBuilder
    {
        private readonly GCodeProgram _program;

        public ProgramBuilder(GCodeProgram program)
        {
            _program = program;
        }

        public GCodeProgram Program => _program;

        // --- Comments ------------------------------------------------------

        /// <summary>Adds a comment line "(text)".</summary>
        public void Comment(string text)
        {
            _program.Blocks.Add(new GCodeBlock(null, text));
        }

        // --- Moves ----------------------------------------------------------

        /// <summary>Rapid move (G0) to the given axes; omitted axes are not emitted.</summary>
        public void RapidTo(double? x = null, double? y = null, double? z = null, double? feed = null, int decimals = -1)
            => Move(0, x, y, z, feed, null, null, decimals);

        /// <summary>Linear move (G1) to the given axes; omitted axes are not emitted.</summary>
        public void LinearTo(double? x = null, double? y = null, double? z = null, double? feed = null, int decimals = -1)
            => Move(1, x, y, z, feed, null, null, decimals);

        /// <summary>Clockwise arc (G2) to (x, y) with center offsets (i, j).</summary>
        public void ArcCW(double x, double y, double i, double j, double feed, int decimals)
            => Move(2, x, y, null, feed, i, j, decimals);

        /// <summary>Counter-clockwise arc (G3) to (x, y) with center offsets (i, j).</summary>
        public void ArcCCW(double x, double y, double i, double j, double feed, int decimals)
            => Move(3, x, y, null, feed, i, j, decimals);

        private void Move(int gCode, double? x, double? y, double? z, double? feed, double? i, double? j, int decimals)
        {
            var words = new List<GCodeWord> { GCodeWord.G(gCode) };
            if (x.HasValue) words.Add(GCodeWord.X(x.Value, decimals));
            if (y.HasValue) words.Add(GCodeWord.Y(y.Value, decimals));
            if (z.HasValue) words.Add(GCodeWord.Z(z.Value, decimals));
            if (i.HasValue) words.Add(GCodeWord.I(i.Value, decimals));
            if (j.HasValue) words.Add(GCodeWord.J(j.Value, decimals));
            if (feed.HasValue) words.Add(GCodeWord.F(feed.Value, decimals));
            _program.Blocks.Add(new GCodeBlock(words));
        }

        // --- Dwell / spindle / coolant --------------------------------------

        /// <summary>Dwell (G4 P&lt;milliseconds&gt;).</summary>
        public void Dwell(double milliseconds)
        {
            AddCode(GCodeWord.G(4), GCodeWord.P(milliseconds));
        }

        /// <summary>
        /// Spindle start (M3 clockwise / M4 counter-clockwise); appends S&lt;rpm&gt;
        /// when <paramref name="rpm"/> is positive.
        /// </summary>
        public void SpindleOn(string command, int rpm = 0)
        {
            var code = string.Equals(command, "M4", System.StringComparison.OrdinalIgnoreCase) ? 4 : 3;
            if (rpm > 0)
                AddCode(GCodeWord.M(code), GCodeWord.S(rpm));
            else
                AddCode(GCodeWord.M(code));
        }

        /// <summary>Spindle stop (M5).</summary>
        public void SpindleOff()
        {
            AddCode(GCodeWord.M(5));
        }

        /// <summary>Coolant on (M8).</summary>
        public void CoolantOn()
        {
            AddCode(GCodeWord.M(8));
        }

        /// <summary>Coolant off (M9).</summary>
        public void CoolantOff()
        {
            AddCode(GCodeWord.M(9));
        }

        // --- Program frame ----------------------------------------------------

        /// <summary>Program header comment.</summary>
        public void Header()
        {
            Comment("Generated by GCodeGenerator");
        }

        /// <summary>Work coordinate system (G54-G59).</summary>
        public void SetWcs(string wcs)
        {
            if (string.IsNullOrEmpty(wcs) || wcs[0] != 'G' || !int.TryParse(wcs.Substring(1), out var code) || code < 54 || code > 59)
                throw new ArgumentException("Work coordinate system must be G54-G59.", nameof(wcs));
            AddCode(GCodeWord.G(code));
        }

        /// <summary>
        /// Start position (G92 X.. Y.. Z..). Legacy behavior: G92 and the
        /// coordinates are never padded/decimal-formatted, hence the raw word.
        /// </summary>
        public void SetStartPosition(double x, double y, double z)
        {
            AddCode(GCodeWord.Raw("G92"), GCodeWord.X(x, -1), GCodeWord.Y(y, -1), GCodeWord.Z(z, -1));
        }

        /// <summary>End position: rapid (G0) to (x, y, z), plain coordinates.</summary>
        public void SetEndPosition(double x, double y, double z)
        {
            RapidTo(x, y, z);
        }

        /// <summary>Program end (M30). Legacy behavior: M30 is never padded.</summary>
        public void EndProgram()
        {
            AddCode(GCodeWord.Raw("M30"));
        }

        private void AddCode(params GCodeWord[] words)
        {
            _program.Blocks.Add(new GCodeBlock(words));
        }
    }
}
