using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using GCodeGenerator.Models;

namespace GCodeGenerator.GCodeGenerators
{
    public class SimpleGCodeGenerator : IGCodeGenerator
    {
        private readonly Dictionary<Type, IOperationGenerator> _generators = new Dictionary<Type, IOperationGenerator>();

        public SimpleGCodeGenerator()
        {
            LoadGenerators();
        }

        private void LoadGenerators()
        {
            var assembly = Assembly.GetExecutingAssembly();
            var generatorTypes = assembly.GetTypes()
                .Where(t => typeof(IOperationGenerator).IsAssignableFrom(t) 
                    && !t.IsInterface 
                    && !t.IsAbstract);

            foreach (var generatorType in generatorTypes)
            {
                var generator = (IOperationGenerator)Activator.CreateInstance(generatorType);
                var operationTypeName = generatorType.Name.Replace("Generator", "");
                
                var operationType = AppDomain.CurrentDomain.GetAssemblies()
                    .SelectMany(a => a.GetTypes())
                    .FirstOrDefault(t => t.Name == operationTypeName && typeof(OperationBase).IsAssignableFrom(t));
                
                if (operationType != null)
                {
                    _generators[operationType] = generator;
                }
            }
        }

        public GCodeProgram Generate(IList<OperationBase> operations, GCodeSettings settings)
        {
            var program = new GCodeProgram();
            var lineNumber = settings.UseLineNumbers ? settings.LineNumberStart : 0;
            string FormatG(string code)
            {
                if (!settings.UsePaddedGCodes)
                    return code;
                if (code.Length >= 2 && code[0] == 'G')
                {
                    if (int.TryParse(code.Substring(1), out var n))
                        return $"G{n:00}";
                }
                return code;
            }

            var g0 = FormatG("G0");
            var g1 = FormatG("G1");
            var g4 = FormatG("G4");
            string FormatM(string code)
            {
                if (!settings.UsePaddedGCodes)
                    return code;
                if (code.Length >= 2 && (code[0] == 'M' || code[0] == 'm'))
                {
                    if (int.TryParse(code.Substring(1), out var n))
                        return $"M{n:00}";
                }
                return code.ToUpperInvariant();
            }

            void AddLine(string code)
            {
                if (settings.UseLineNumbers)
                {
                    program.Lines.Add($"N{lineNumber} {code}");
                    lineNumber += settings.LineNumberStep;
                }
                else
                {
                    program.Lines.Add(code);
                }
            }

            AddLine("(Generated by GCodeGenerator)");

            // Установка рабочей системы координат (G54-G59) в самом начале программы
            if (settings.SetWorkCoordinateSystem && !string.IsNullOrEmpty(settings.WorkCoordinateSystem))
            {
                var wcs = settings.WorkCoordinateSystem.Trim().ToUpperInvariant();
                // Проверяем, что это валидная команда G54-G59
                if (wcs == "G54" || wcs == "G55" || wcs == "G56" || wcs == "G57" || wcs == "G58" || wcs == "G59")
                {
                    AddLine(FormatG(wcs));
                }
            }

            // Установка стартовых координат (G92) сразу после комментариев
            if (settings.AddStartPosition)
            {
                var sx = settings.StartX.ToString(CultureInfo.InvariantCulture);
                var sy = settings.StartY.ToString(CultureInfo.InvariantCulture);
                var sz = settings.StartZ.ToString(CultureInfo.InvariantCulture);
                AddLine($"G92 X{sx} Y{sy} Z{sz}");
            }

            void AddSpindlePreamble()
            {
                if (!settings.SpindleControlEnabled)
                    return;

                if (settings.SpindleStartEnabled)
                {
                    var cmd = (settings.SpindleStartCommand ?? "M3").Trim().ToUpperInvariant();
                    if (cmd != "M3" && cmd != "M4")
                        cmd = "M3";
                    var startCmd = FormatM(cmd);
                    if (settings.SpindleSpeedEnabled)
                        AddLine($"{startCmd} S{settings.SpindleSpeedRpm}");
                    else
                        AddLine(startCmd);
                }

                AddCoolantStart();

                if (settings.SpindleDelayEnabled && settings.SpindleDelaySeconds > 0)
                {
                    var delayMs = settings.SpindleDelaySeconds * 1000.0;
                    AddLine($"{g4} P{delayMs.ToString(CultureInfo.InvariantCulture)}");
                }
            }

            void AddCoolantStart()
            {
                if (!settings.CoolantControlEnabled || !settings.CoolantStartEnabled)
                    return;
                AddLine(FormatM("M8"));
            }

            void AddCoolantStop()
            {
                if (!settings.CoolantControlEnabled || !settings.CoolantStopEnabled)
                    return;
                AddLine(FormatM("M9"));
            }

            AddSpindlePreamble();

            foreach (var operation in operations)
            {
                // Skip disabled operations completely when generating trajectory
                if (operation == null || !operation.IsEnabled)
                    continue;

                if (settings.UseComments)
                    AddLine($"({operation.Name}: {operation.GetDescription()})");

                var operationType = operation.GetType();
                if (_generators.TryGetValue(operationType, out var generator))
                {
                    generator.Generate(operation, AddLine, g0, g1, settings);
                }
            }

            AddCoolantStop();

            if (settings.AddEndPosition)
            {
                var ex = settings.EndX.ToString(CultureInfo.InvariantCulture);
                var ey = settings.EndY.ToString(CultureInfo.InvariantCulture);
                var ez = settings.EndZ.ToString(CultureInfo.InvariantCulture);
                AddLine($"{g0} X{ex} Y{ey} Z{ez}");
            }

            if (settings.SpindleControlEnabled && settings.SpindleStopEnabled)
                AddLine(FormatM("M5"));

            AddLine("M30");
            return program;
        }
    }
}


