using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using GCodeGenerator.Models;

namespace GCodeGenerator.GCodeGenerators
{
    public class SimpleGCodeGenerator : IGCodeGenerator
    {
        private readonly Dictionary<Type, IOperationGenerator> _generators = new Dictionary<Type, IOperationGenerator>();

        public SimpleGCodeGenerator()
        {
            LoadGenerators();
        }

        private void LoadGenerators()
        {
            var assembly = Assembly.GetExecutingAssembly();
            var generatorTypes = assembly.GetTypes()
                .Where(t => typeof(IOperationGenerator).IsAssignableFrom(t) 
                    && !t.IsInterface 
                    && !t.IsAbstract);

            foreach (var generatorType in generatorTypes)
            {
                var generator = (IOperationGenerator)Activator.CreateInstance(generatorType);
                var operationTypeName = generatorType.Name.Replace("Generator", "");
                
                var operationType = AppDomain.CurrentDomain.GetAssemblies()
                    .SelectMany(a => a.GetTypes())
                    .FirstOrDefault(t => t.Name == operationTypeName && typeof(OperationBase).IsAssignableFrom(t));
                
                if (operationType != null)
                {
                    _generators[operationType] = generator;
                }
            }
        }

        public GCodeProgram Generate(IList<OperationBase> operations, GCodeSettings settings)
        {
            var program = new GCodeProgram();
            var lineNumber = settings.UseLineNumbers ? settings.LineNumberStart : 0;
            string FormatG(string code)
            {
                if (!settings.UsePaddedGCodes)
                    return code;
                if (code.Length >= 2 && code[0] == 'G')
                {
                    if (int.TryParse(code.Substring(1), out var n))
                        return $"G{n:00}";
                }
                return code;
            }

            var g0 = FormatG("G0");
            var g1 = FormatG("G1");

            void AddLine(string code)
            {
                if (settings.UseLineNumbers)
                {
                    program.Lines.Add($"N{lineNumber} {code}");
                    lineNumber += settings.LineNumberStep;
                }
                else
                {
                    program.Lines.Add(code);
                }
            }

            AddLine("(Generated by GCodeGenerator)");

            foreach (var operation in operations)
            {
                if (settings.UseComments)
                    AddLine($"({operation.Name}: {operation.GetDescription()})");

                var operationType = operation.GetType();
                if (_generators.TryGetValue(operationType, out var generator))
                {
                    generator.Generate(operation, AddLine, g0, g1, settings);
                }
            }

            AddLine("M30");
            return program;
        }
    }
}


